import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Col, Row} from "react-bootstrap";
import MyTodos from "../components/todos";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={'mb-5'}>React-toolkit</h1>
                <Row>
                    {/*<Col>*/}
                    {/*    /!*<Users/>*!/*/}
                    {/*</Col>*/}
                    <Col>
                        <MyTodos/>
                    </Col>
                </Row>
            </main>
        </div>
    )
}
